name: CI
# bla bla bla
on:
  pull_request:
    branches: [ main ]
# use secrets ${{ secrets.MY_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn clean install
